//! svd2zig — minimal CMSIS-SVD → Zig generator (host tool, run by build.zig).
//!
//! Usage: svd2zig <input.svd> <output.zig>
//!
//! Emits one `pub const <PERIPHERAL> = struct { … }` per peripheral, with
//! `base` and a `pub const <REG>: u32 = base + offset;` for every register —
//! absolute MMIO addresses, data only (no functions), so the generated module
//! is safe to import on the prebuilt xtensa backend. Register `<dim>` arrays are
//! expanded; `derivedFrom` peripherals get their base address only.

const std = @import("std");
const Io = std.Io;
const ArrayList = std.ArrayList(u8);

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) {
        std.debug.print("usage: {s} <input.svd> <output.zig>\n", .{args[0]});
        std.process.exit(2);
    }

    const cwd = Io.Dir.cwd();
    const svd = try cwd.readFileAlloc(init.io, args[1], gpa, .unlimited);

    var out: ArrayList = .empty;
    try out.print(gpa, "// Generated by tools/svd2zig.zig from {s}. Do not edit.\n\n", .{std.fs.path.basename(args[1])});
    try generate(gpa, &out, svd);

    const f = try cwd.createFile(init.io, args[2], .{});
    defer f.close(init.io);
    try f.writeStreamingAll(init.io, out.items);
}

fn generate(gpa: std.mem.Allocator, out: *ArrayList, svd: []const u8) !void {
    const periphs = sliceBetween(svd, "<peripherals>", "</peripherals>", 0) orelse return error.NoPeripherals;
    var cur = periphs.from;
    while (std.mem.indexOfPos(u8, svd, cur, "<peripheral")) |open| {
        if (open >= periphs.to) break;
        const tag_end = std.mem.indexOfScalarPos(u8, svd, open, '>') orelse break;
        const close = std.mem.indexOfPos(u8, svd, tag_end, "</peripheral>") orelse break;
        const block = svd[open..close];
        cur = close + "</peripheral>".len;

        const name = tagText(block, "name") orelse continue;
        const base = parseInt(tagText(block, "baseAddress") orelse continue) orelse continue;
        const derived = std.mem.indexOf(u8, svd[open..tag_end], "derivedFrom=") != null;

        if (tagText(block, "description")) |d| try out.print(gpa, "/// {s}\n", .{oneLine(d)});
        try out.appendSlice(gpa, "pub const ");
        try appendIdent(gpa, out, name, null);
        try out.print(gpa, " = struct {{\n    pub const base: u32 = 0x{X};\n", .{base});
        if (!derived) try emitRegisters(gpa, out, block);
        try out.appendSlice(gpa, "};\n\n");
    }
}

fn emitRegisters(gpa: std.mem.Allocator, out: *ArrayList, periph: []const u8) !void {
    const regs = sliceBetween(periph, "<registers>", "</registers>", 0) orelse return;
    var cur = regs.from;
    while (std.mem.indexOfPos(u8, periph, cur, "<register>")) |open| {
        if (open >= regs.to) break;
        const close = std.mem.indexOfPos(u8, periph, open, "</register>") orelse break;
        const block = periph[open..close];
        cur = close + "</register>".len;

        const name = tagText(block, "name") orelse continue;
        const off = parseInt(tagText(block, "addressOffset") orelse continue) orelse continue;

        const dim = if (tagText(block, "dim")) |d| (parseInt(d) orelse 0) else 0;
        const inc = if (tagText(block, "dimIncrement")) |d| (parseInt(d) orelse 0) else 0;
        if (dim > 0) {
            var k: u64 = 0;
            while (k < dim) : (k += 1) try emitReg(gpa, out, name, k, off + k * inc);
        } else {
            try emitReg(gpa, out, name, null, off);
        }
    }
}

fn emitReg(gpa: std.mem.Allocator, out: *ArrayList, name: []const u8, dim: ?u64, addr: u64) !void {
    try out.appendSlice(gpa, "    pub const ");
    try appendIdent(gpa, out, name, dim);
    try out.print(gpa, ": u32 = base + 0x{X};\n", .{addr});
}

// ── tiny XML helpers ──────────────────────────────────────────────────────────

const Span = struct { from: usize, to: usize };

fn sliceBetween(h: []const u8, open: []const u8, close: []const u8, from: usize) ?Span {
    const o = std.mem.indexOfPos(u8, h, from, open) orelse return null;
    const start = o + open.len;
    const c = std.mem.indexOfPos(u8, h, start, close) orelse return null;
    return .{ .from = start, .to = c };
}

/// Trimmed text of the first `<tag>…</tag>` in `h`.
fn tagText(h: []const u8, comptime tag: []const u8) ?[]const u8 {
    const s = sliceBetween(h, "<" ++ tag ++ ">", "</" ++ tag ++ ">", 0) orelse return null;
    return std.mem.trim(u8, h[s.from..s.to], " \t\r\n");
}

fn parseInt(s: []const u8) ?u64 {
    return std.fmt.parseInt(u64, std.mem.trim(u8, s, " \t\r\n"), 0) catch null;
}

fn oneLine(s: []const u8) []const u8 {
    const t = std.mem.trim(u8, s, " \t\r\n");
    return t[0..(std.mem.indexOfScalar(u8, t, '\n') orelse t.len)];
}

/// Append `name` as a valid Zig identifier: drop `%s`/`[`/`]` placeholders,
/// map other non-alphanumerics to `_`, prefix `_` if it would start with a
/// digit, then append `_<dim>` when this is a `<dim>` array element.
fn appendIdent(gpa: std.mem.Allocator, out: *ArrayList, name: []const u8, dim: ?u64) !void {
    var first = true;
    var i: usize = 0;
    while (i < name.len) : (i += 1) {
        const c = name[i];
        if (c == '%' and i + 1 < name.len and name[i + 1] == 's') {
            i += 1;
            continue;
        }
        if (c == '[' or c == ']') continue;
        const ch: u8 = if (std.ascii.isAlphanumeric(c) or c == '_') c else '_';
        if (first and !std.ascii.isAlphabetic(ch) and ch != '_') try out.append(gpa, '_');
        try out.append(gpa, ch);
        first = false;
    }
    if (dim) |k| try out.print(gpa, "_{d}", .{k});
}
