// Copyright (c) 2026 Matheus C. França
// SPDX-License-Identifier: Apache-2.0

//! svd2zig — minimal CMSIS-SVD → Zig generator (host tool, run by build.zig).
//!
//! Usage: svd2zig <input.svd> <output.zig>
//!
//! Emits one `pub const <PERIPHERAL> = struct { … }` per peripheral, with
//! `base` and a `pub const <REG>: u32 = base + offset;` for every register —
//! absolute MMIO addresses, data only (no functions), so the generated module
//! is safe to import on the prebuilt xtensa backend.
//!
//! Handles the full esp-pacs SVDs (any esp32* target, Xtensa or RISC-V):
//! `<dim>` arrays are expanded, nested `<cluster>`s flatten to prefixed names
//! with accumulated offsets, `derivedFrom` peripherals reuse the parent's
//! registers, and any residual name collision is suffixed so the output always
//! compiles.

const std = @import("std");
const Io = std.Io;
const ArrayList = std.ArrayList(u8);

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 3) {
        std.debug.print("usage: {s} <input.svd> <output.zig>\n", .{args[0]});
        std.process.exit(2);
    }

    const cwd = Io.Dir.cwd();
    const svd = try cwd.readFileAlloc(init.io, args[1], gpa, .unlimited);

    var out: ArrayList = .empty;
    try out.print(gpa, "// Generated by tools/svd2zig.zig from {s}. Do not edit.\n\n", .{std.fs.path.basename(args[1])});
    try generate(gpa, &out, svd);

    const f = try cwd.createFile(init.io, args[2], .{});
    defer f.close(init.io);
    try f.writeStreamingAll(init.io, out.items);
}

fn generate(gpa: std.mem.Allocator, out: *ArrayList, svd: []const u8) !void {
    const periphs = sliceBetween(svd, "<peripherals>", "</peripherals>", 0) orelse return error.NoPeripherals;

    // First pass: record each peripheral's block by name so `derivedFrom`
    // peripherals (e.g. TIMG1 from TIMG0) can reuse the parent's registers.
    var blocks = std.StringHashMap([]const u8).init(gpa);
    var it = PeriphIter{ .svd = svd, .cur = periphs.from, .to = periphs.to };
    while (it.next()) |p| if (tagText(p.block, "name")) |n| try blocks.put(n, p.block);

    it = PeriphIter{ .svd = svd, .cur = periphs.from, .to = periphs.to };
    while (it.next()) |p| {
        const name = tagText(p.block, "name") orelse continue;
        const base = parseInt(tagText(p.block, "baseAddress") orelse continue) orelse continue;

        if (tagText(p.block, "description")) |d| try out.print(gpa, "/// {s}\n", .{oneLine(d)});
        try out.appendSlice(gpa, "pub const ");
        try appendIdent(gpa, out, name, null);
        try out.print(gpa, " = struct {{\n    pub const base: u32 = 0x{X};\n", .{base});
        // Registers come from this peripheral, or from its `derivedFrom` parent.
        const regs_block = if (attrValue(svd[p.open..p.tag_end], "derivedFrom")) |parent|
            (blocks.get(parent) orelse p.block)
        else
            p.block;
        try emitRegisters(gpa, out, regs_block);
        try out.appendSlice(gpa, "};\n\n");
    }
}

const Periph = struct { block: []const u8, open: usize, tag_end: usize };

const PeriphIter = struct {
    svd: []const u8,
    cur: usize,
    to: usize,

    fn next(self: *PeriphIter) ?Periph {
        const open = std.mem.indexOfPos(u8, self.svd, self.cur, "<peripheral") orelse return null;
        if (open >= self.to) return null;
        const tag_end = std.mem.indexOfScalarPos(u8, self.svd, open, '>') orelse return null;
        const close = std.mem.indexOfPos(u8, self.svd, tag_end, "</peripheral>") orelse return null;
        self.cur = close + "</peripheral>".len;
        return .{ .block = self.svd[open..close], .open = open, .tag_end = tag_end };
    }
};

/// Value of `attr="..."` within an opening tag, or null.
fn attrValue(tag: []const u8, comptime attr: []const u8) ?[]const u8 {
    const k = std.mem.indexOf(u8, tag, attr ++ "=\"") orelse return null;
    const start = k + attr.len + 2;
    const end = std.mem.indexOfScalarPos(u8, tag, start, '"') orelse return null;
    return tag[start..end];
}

fn emitRegisters(gpa: std.mem.Allocator, out: *ArrayList, periph: []const u8) !void {
    const regs = sliceBetween(periph, "<registers>", "</registers>", 0) orelse return;
    var used = std.StringHashMap(void).init(gpa);
    try emitContainer(gpa, out, periph[regs.from..regs.to], "", 0, &used);
}

/// Walk the immediate `<register>` / `<cluster>` children of `content`, emitting
/// one `pub const` per register. Recurses into clusters, accumulating an
/// identifier `prefix` and an address `base_off` and expanding `<dim>` at every
/// level — so nested/array register groups flatten to unique, correctly-addressed
/// names instead of colliding bare ones.
fn emitContainer(gpa: std.mem.Allocator, out: *ArrayList, content: []const u8, prefix: []const u8, base_off: u64, used: *std.StringHashMap(void)) std.mem.Allocator.Error!void {
    var cur: usize = 0;
    while (cur < content.len) {
        const ro = std.mem.indexOfPos(u8, content, cur, "<register>");
        const co = std.mem.indexOfPos(u8, content, cur, "<cluster>");
        if (co != null and (ro == null or co.? < ro.?)) {
            const inner = co.? + "<cluster>".len;
            const close = matchClusterClose(content, inner) orelse break;
            try emitCluster(gpa, out, content[inner..close], prefix, base_off, used);
            cur = close + "</cluster>".len;
        } else if (ro) |open| {
            const close = std.mem.indexOfPos(u8, content, open, "</register>") orelse break;
            try emitRegister(gpa, out, content[open + "<register>".len .. close], prefix, base_off, used);
            cur = close + "</register>".len;
        } else break;
    }
}

fn emitCluster(gpa: std.mem.Allocator, out: *ArrayList, block: []const u8, prefix: []const u8, base_off: u64, used: *std.StringHashMap(void)) std.mem.Allocator.Error!void {
    const name = tagText(block, "name") orelse return;
    const off = parseInt(tagText(block, "addressOffset") orelse "0x0") orelse 0;
    const d = Dim.parse(block);
    var k: u64 = 0;
    while (k < d.count) : (k += 1) {
        const id = try identStr(gpa, name, d.indexOf(k));
        const child_prefix = try std.fmt.allocPrint(gpa, "{s}{s}_", .{ prefix, id });
        try emitContainer(gpa, out, block, child_prefix, base_off + off + k * d.inc, used);
    }
}

fn emitRegister(gpa: std.mem.Allocator, out: *ArrayList, block: []const u8, prefix: []const u8, base_off: u64, used: *std.StringHashMap(void)) !void {
    const name = tagText(block, "name") orelse return;
    const off = parseInt(tagText(block, "addressOffset") orelse return) orelse return;
    const d = Dim.parse(block);
    var k: u64 = 0;
    while (k < d.count) : (k += 1)
        try emitConst(gpa, out, prefix, try identStr(gpa, name, d.indexOf(k)), base_off + off + k * d.inc, used);
}

/// A register/cluster's `<dim>`/`<dimIncrement>`. A non-array element parses as
/// one repetition with no index, so callers iterate `0..count` uniformly.
const Dim = struct {
    count: u64,
    inc: u64,
    array: bool,

    fn parse(block: []const u8) Dim {
        const d = tagText(block, "dim") orelse return .{ .count = 1, .inc = 0, .array = false };
        return .{
            .count = parseInt(d) orelse 1,
            .inc = if (tagText(block, "dimIncrement")) |i| parseInt(i) orelse 0 else 0,
            .array = true,
        };
    }

    /// Index suffix for element `k` — `null` (no suffix) unless this is an array.
    fn indexOf(self: Dim, k: u64) ?u64 {
        return if (self.array) k else null;
    }
};

fn emitConst(gpa: std.mem.Allocator, out: *ArrayList, prefix: []const u8, id: []const u8, addr: u64, used: *std.StringHashMap(void)) !void {
    const ident = if (prefix.len == 0) id else try std.fmt.allocPrint(gpa, "{s}{s}", .{ prefix, id });
    try out.print(gpa, "    pub const {s}: u32 = base + 0x{X};\n", .{ try uniqueName(gpa, used, ident), addr });
}

/// Find the `</cluster>` that closes the cluster opened just before `from`,
/// balancing nested `<cluster>` … `</cluster>` pairs.
fn matchClusterClose(h: []const u8, from: usize) ?usize {
    var depth: usize = 1;
    var i = from;
    while (true) {
        const close = std.mem.indexOfPos(u8, h, i, "</cluster>") orelse return null;
        const open = std.mem.indexOfPos(u8, h, i, "<cluster>");
        if (open != null and open.? < close) {
            depth += 1;
            i = open.? + "<cluster>".len;
        } else {
            depth -= 1;
            if (depth == 0) return close;
            i = close + "</cluster>".len;
        }
    }
}

/// Return `ident` if unused, else the first `ident_N` (N≥2) that is free, so a
/// peripheral never emits two `pub const`s with the same name (which won't
/// compile). Defensive — proper cluster prefixes already make most names unique.
fn uniqueName(gpa: std.mem.Allocator, used: *std.StringHashMap(void), ident: []const u8) ![]const u8 {
    if (!used.contains(ident)) {
        try used.put(ident, {});
        return ident;
    }
    var n: u32 = 2;
    while (true) : (n += 1) {
        const cand = try std.fmt.allocPrint(gpa, "{s}_{d}", .{ ident, n });
        if (!used.contains(cand)) {
            try used.put(cand, {});
            return cand;
        }
    }
}

/// Sanitize `name` into a Zig identifier (see `appendIdent`) and return it as an
/// owned slice, appending `_<dim>` for `<dim>` array elements.
fn identStr(gpa: std.mem.Allocator, name: []const u8, dim: ?u64) ![]const u8 {
    var buf: ArrayList = .empty;
    try appendIdent(gpa, &buf, name, dim);
    return buf.items;
}

// ── tiny XML helpers ──────────────────────────────────────────────────────────

const Span = struct { from: usize, to: usize };

fn sliceBetween(h: []const u8, open: []const u8, close: []const u8, from: usize) ?Span {
    const o = std.mem.indexOfPos(u8, h, from, open) orelse return null;
    const start = o + open.len;
    const c = std.mem.indexOfPos(u8, h, start, close) orelse return null;
    return .{ .from = start, .to = c };
}

/// Trimmed text of the first `<tag>…</tag>` in `h`.
fn tagText(h: []const u8, comptime tag: []const u8) ?[]const u8 {
    const s = sliceBetween(h, "<" ++ tag ++ ">", "</" ++ tag ++ ">", 0) orelse return null;
    return std.mem.trim(u8, h[s.from..s.to], " \t\r\n");
}

fn parseInt(s: []const u8) ?u64 {
    return std.fmt.parseInt(u64, std.mem.trim(u8, s, " \t\r\n"), 0) catch null;
}

fn oneLine(s: []const u8) []const u8 {
    const t = std.mem.trim(u8, s, " \t\r\n");
    return t[0..(std.mem.indexOfScalar(u8, t, '\n') orelse t.len)];
}

/// Append `name` as a valid Zig identifier: drop `%s`/`[`/`]` placeholders,
/// map other non-alphanumerics to `_`, prefix `_` if it would start with a
/// digit, then append `_<dim>` when this is a `<dim>` array element.
fn appendIdent(gpa: std.mem.Allocator, out: *ArrayList, name: []const u8, dim: ?u64) !void {
    var first = true;
    var i: usize = 0;
    while (i < name.len) : (i += 1) {
        const c = name[i];
        if (c == '%' and i + 1 < name.len and name[i + 1] == 's') {
            i += 1;
            continue;
        }
        if (c == '[' or c == ']') continue;
        const ch: u8 = if (std.ascii.isAlphanumeric(c) or c == '_') c else '_';
        if (first and !std.ascii.isAlphabetic(ch) and ch != '_') try out.append(gpa, '_');
        try out.append(gpa, ch);
        first = false;
    }
    if (dim) |k| try out.print(gpa, "_{d}", .{k});
}
